import "../styles/global.css";
import Link from "next/link";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
// This default export is required in a new `pages/_app.js` file.
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Blog Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>BLOG WEB</h1>

      <ul>
        <li>
          <Link href="/createPost">
            <a>Create Post</a>
          </Link>
        </li>
        <li>
          <Link href="/postList">
            <a>Post List</a>
          </Link>
        </li>
      </ul>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
